config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  delete 'courses/remove_student/:id', to: 'courses#remove_student'
  post 'courses/add_student/:id', to: 'courses#add_student'

  get 'docs/tut_ballot_tips'

  get 'docs/tut_step1'

  get 'docs/tut_step2'

  get 'tutorials/view'

  get 'tutorials/select'

  post 'tutorials/select_save', to: 'tutorials#select_save'

  get 'tutorials/rank'

  post 'tutorials/rank_save', to: 'tutorials#rank_save'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :courses
  resources :lectures
  resources :tutorials

  root 'sessions#new'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy,
                                      :add_student, :remove_student]
  before_action :authorize_admin

  # GET /courses
  def index
    @edit_all_courses = Course.all
  end

  # GET /courses/new
  def new
    @edit_course = Course.new
  end

  # POST /courses
  def create
    @edit_course = Course.new(course_params)

    respond_to do |format|
      if @edit_course.save
        format.html { redirect_to @edit_course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @edit_course }
      else
        format.html { render :new }
        format.json { render json: @edit_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @edit_course.update(course_params)
        format.html { redirect_to @edit_course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @edit_course }
      else
        format.html { render :edit }
        format.json { render json: @edit_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    respond_to do |format|
      if @edit_course.destroy
        format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to courses_url,
          alert: 'Illegal Operation: Ensure that all users are no longer enrolled, and all lectures/tutorials are deleted.' }
        format.json { head :no_content }
      end
    end
  end

  def show
    @edit_enrolled = @edit_course.users
  end

  # POST /courses/add_student/:course_id?student=id
  def add_student
    courseId = params[:id]
    studentId = params[:student]

    respond_to do |format|
      if UserCourseSelection.find_by(course_id: courseId, user_id: studentId)
        format.html { redirect_to @edit_course, alert: 'This student is already in the course!' }
        format.json { head :no_content }
      else
        record = UserCourseSelection.new(course_id: courseId, user_id: studentId)

        if record.save
          format.html { redirect_to @edit_course, notice: 'Student added successfully' }
          format.json { head :no_content }
        else
          format.html { redirect_to @edit_course, alert: 'Fail to add student, errors' + @edit_course.errors.full_messages }
          format.json { render json: @edit_course.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE/courses/remove_student/:course_id?student=id
  def remove_student
    courseId = params[:id]
    studentId = params[:student]

    record = find_student(courseId, studentId)
    if record
      also_delete_tutorial_selections(studentId)
      record.delete
    end

    respond_to do |format|
      format.html { redirect_to @edit_course, notice: 'Student removed' }
      format.json { head :no_content }
    end
  end

  def edit
  end

  private
    def also_delete_tutorial_selections(student_id)
      # Wang Leng: This is probably my fault. UserTutorialSelection
      # should be related to UserCourseSelection so that when the
      # user drops the course, it also drops all tutorial selections.
      # However, this relationship does not exist in the database,
      # and the changes required is more than just merely adding
      # a single foreign key, therefore, we will have to do it
      # manually by executing this method.

      @edit_course.tutorials.each do |tut|
        tut_selection = UserTutorialSelection.find_by(user_id: student_id, tutorial_id: tut.id)
        if tut_selection.nil? == false
          tut_selection.delete
        end
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @edit_course = Course.find(params[:id])
    end

  private
    def find_student(courseId, studentId)
      return UserCourseSelection.find_by(course_id: courseId, user_id: studentId)
    end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :code)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@edit_course) do |f| %>
  <%= render partial: "layouts/db_record_errors", locals: { current_record: @edit_course } %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <hr>
<% end %>

app/views/courses/edit.html.erb
<div class="container">
  <h1>Editing Course</h1>

  <%= render 'form' %>

  <br>
  <%= link_to 'Discard Changes', @edit_course, class: "btn btn-danger" %>
  <% # link_to 'Discard and Return to List', courses_path, class: "btn btn-danger" %>
</div>

app/views/courses/index.html.erb
<div class="container">
  <h1>Listing Courses</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>(Actions)</th>
      </tr>
    </thead>

    <tbody>
      <% @edit_all_courses.each do |course| %>
        <tr>
          <td>[Code: <%= course.code %>] <%= course.name %></td>
          <td>
            <%= link_to 'Show', course, class: "btn btn-primary" %>
            <% # link_to 'Edit', edit_course_path(course), class: "btn btn-info" %>
            <%= link_to 'Destroy', course, class: "btn btn-danger" , method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <hr>
  <%= link_to 'New Course', new_course_path, class: "btn btn-primary" %>
</div>

app/views/courses/new.html.erb
<div class="container">
  <h1>New Course</h1>
  <%= render 'form' %>

  <br>
  <%= link_to 'Cancel', courses_path, class: "btn btn-danger" %>
</div>

app/views/courses/show.html.erb
<div class="container">
  <h1>Viewing Course '<%= @edit_course.name %>'</h1>

  <!-- Info -->
  <h2>Basic Information</h2>
  <ul>
    <li><strong>Code:</strong> <%= @edit_course.code %></li>
    <li><strong>Name:</strong> <%= @edit_course.name %></li>
  </ul>

  <%= link_to 'Edit Course', edit_course_path(@edit_course), class: "btn btn-primary" %>

  <!-- Enrolled students -->
  <hr>
  <h2>Enrolled Students</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Matric Number</th>
        <th>(Actions)</th>
    </thead>

    <tbody>
      <% if @edit_enrolled.empty? %>
        <tr><td colspan="2">No students are enrolled into the course.</td></tr>
      <% else %>
        <% @edit_enrolled.each do |student| %>
          <tr>
            <td><%= student.matricNo %></td>
            <td><%= link_to 'Remove',
             { action: :remove_student, params: { student: student.id } },
             method: :delete,
             class: "btn btn-danger",
             data: { confirm: 'Are you sure? WARNING: All tutorial slots for this student will be dropped!' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <%= form_tag({ action: :add_student, id: @edit_course.id }, method: :post) do %>
    Add student to course:
    <%= select_tag "student", options_from_collection_for_select(User.all, :id, :matricNo) %>
    <%= submit_tag "Add", class:"btn btn-primary" %>
  <% end %>

  <br>

  <!-- Lectures -->
  <hr>
  <h2>Lectures</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Group Number</th>
        <th>Day</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>(Actions)</th>
    </thead>

    <tbody>
      <% if @edit_course.lectures.empty? %>
        <tr><td colspan="5">There is no lecture for this course.</td></tr>
      <% else %>
        <% @edit_course.lectures.each do |lec| %>
          <tr>
            <td><%= lec.group_number %></td>
            <td><%= getDay(lec.day) %></td>
            <td><%= getHourAndMin(lec.start_time) %></td>
            <td><%= getHourAndMin(lec.end_time) %></td>
            <td>
              <%= link_to 'Edit', edit_lecture_path(lec), class: "btn btn-info" %>
              <%= link_to 'Remove', lec, class: "btn btn-danger" , method: :delete,
                data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New Lecture Time',
    { controller: :lectures, action: :new, params: { course_id: @edit_course.id } },
    class: "btn btn-primary" %>

  <br>

  <!-- Tutorials -->
  <hr>
  <h2>Tutorials</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Group Number</th>
        <th>Odd/Even</th>
        <th>Day</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Day (2nd Slot)</th>
        <th>Start Time (2nd Slot)</th>
        <th>End Time (2nd Slot)</th>
        <th>(Actions)</th>
    </thead>

    <tbody>
      <% if @edit_course.tutorials.empty? %>
        <tr><td colspan="9">There is no tutorial for this course.</td></tr>
      <% else %>
        <% @edit_course.tutorials.each do |tut| %>
          <tr>
            <td><%= tut.group_number %></td>
            <td>
              <% if tut.odd? %>
                Odd
              <% elsif tut.even? %>
                Even
              <% else %>
                Both
              <% end %>
            </td>
            <td><%= getDay(tut.day) %></td>
            <td><%= getHourAndMin(tut.start_time) %></td>
            <td><%= getHourAndMin(tut.end_time) %></td>

            <% if tut.has_second_tutorial? %>
              <td><%= getDay(tut.second_day) %></td>
              <td><%= getHourAndMin(tut.second_start_time) %></td>
              <td><%= getHourAndMin(tut.second_end_time) %></td>
            <% else %>
              <td colspan="3">[No 2nd slot]</td>
            <% end %>

            <td>
              <%= link_to 'Edit', edit_tutorial_path(tut), class: "btn btn-info" %>
              <%= link_to 'Remove', tut, class: "btn btn-danger" , method: :delete,
                data: { confirm: 'Are you sure? WARNING: All students in this tutorial slot will be dropped!' } %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New Tutorial Time',
    { controller: :tutorials, action: :new, params: { course_id: @edit_course.id } },
    class: "btn btn-primary" %>
  <br>

  <hr>
  <br>
  <%= link_to 'Return to Courses List', courses_path, class: "btn btn-success" %>
</div>